### ISSUE TITLE
[KLI]: SR2024 HRS

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/kit-logistics#100]
### Competition Year

SR2024

### Team TLA

HRS

### Asset Code of RUB

1GN24

### How was the kit issued?

Kit shipped via Courier

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by mgrove36** [comment]
Extra motor board and memory stick
Missing camcon and screwdriver
