### ISSUE TITLE
[KLI]: SR2024 HWM

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/kit-logistics#103]
### Competition Year

SR2024

### Team TLA

HWM

### Asset Code of RUB

1JL22

### How was the kit issued?

Kit shipped via Courier

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by mgrove36** [comment]
2x micro USB cables missing and screwdriver
