### ISSUE TITLE
[KLI]: SR2024 HZW

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/kit-logistics#104]
### Competition Year

SR2024

### Team TLA

HZW

### Asset Code of RUB

1MN2T

### How was the kit issued?

Kit shipped via Courier

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by mgrove36** [comment]
2 micro USB cables missing and 2x camcons (but this is the same as they received)
