### ISSUE TITLE
[KLI]: SR2024 RGS

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/kit-logistics#111]
### Competition Year

SR2024

### Team TLA

RGS

### Asset Code of RUB

1VL2E

### How was the kit issued?

Kit shipped via Courier

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by mgrove36** [comment]
Arduino stopped working. 1x micro USB cable missing
