### ISSUE TITLE
[KLI]: SR2024 WMC

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/kit-logistics#117]
### Competition Year

SR2024

### Team TLA

WMC

### Asset Code of RUB

srFR33

### How was the kit issued?

Kit shipped via Courier

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by mgrove36** [comment]
All returned except 1x micro USB cable and 1x screwdriver
