### ISSUE TITLE
[KLI]: SR2022 HAM

### ISSUE THREAD

**Issue by trickeydan** [srobo/kit-logistics#15]
### Competition Year

SR2020

### Team TLA

HAM

### Asset Code of RUB

0VK3E

### How was the kit issued?

In-person (e.g Kickstart)

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by trickeydan** [comment]
**Transfer to SR2022**

    This team is competing in SR2022 and the kit has been held over.

**Comment by trickeydan** [comment]
Returned 0UK3E without a lid at competition

**Comment by trickeydan** [comment]
Chase email sent.

**Comment by trickeydan** [comment]
Chase sent.

**Comment by trickeydan** [comment]
Asked teacher if they are willing to return at Kickstart

**Comment by trickeydan** [comment]
The team leader has confirmed that they will be competing next year. I approve for this to be returned at Kickstart SR2023

**Comment by Tyler-Ward** [comment]
Do we know if this happened at kickstart?

**Comment by RealOrangeOne** [comment]
I don't believe we have any spare RUB lids around. If we do, this is probably it. If we don't, then I suspect it's lost to time. Other items from the kit are present and correct. Either way, no further action.
