### ISSUE TITLE
[KLI]: SR2022 HRS

### ISSUE THREAD

**Issue by trickeydan** [srobo/kit-logistics#16]
### Competition Year

SR2020

### Team TLA

HRS

### Asset Code of RUB

1KM2Y

### How was the kit issued?

In-person (e.g Kickstart)

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by trickeydan** [comment]
**Transfer to SR2022**

    This team is competing in SR2022 and the kit has been held over.

**Comment by trickeydan** [comment]
Returned 1KM2Y at comp with missing parts

**Comment by trickeydan** [comment]
Kit Chase email sent.

**Comment by trickeydan** [comment]
Chase sent

**Comment by trickeydan** [comment]
Teacher replied confirming parts. @antonnikitin97 has kindly agreed to pick them up in person, thanks Anton! 🐝

**Comment by Tyler-Ward** [comment]
The only part they had in the inventory was a ruggeduino which is now in my garage so I assume this happened.
