### ISSUE TITLE
[KLI]: SR2020 JAM

### ISSUE THREAD

**Issue by trickeydan** [srobo/kit-logistics#18]
### Competition Year

SR2020

### Team TLA

JAM

### Asset Code of RUB

1QM2M

### How was the kit issued?

In-person (e.g Kickstart)

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by emersok1** [comment]
Contacted by Phone/Email June2022 (Issue with KE SR email going to Junk. Son(who built robot) should be back from travels by 1st July. Will then remove kit from robot and collate kit. Pics & return info sent. Will require pick-up or help with shipping costs. Jake OK to pick up.

**Comment by RealOrangeOne** [comment]
They're only ~40 minutes down the road from me. Let me know once they've confirmed they have the kit all together and I can coordinate getting the kit collected.

**Comment by RealOrangeOne** [comment]
I've contacted the team leader to arrange a date for me to go and collect it.

**Comment by trickeydan** [comment]
@RealOrangeOne Did you mean to remove the label? Has the kit now been collected?

**Comment by RealOrangeOne** [comment]
It hasn't, no. But the action is in hand and in progress, so I removed the label. Otherwise the label doesn't really mean anything.

**Comment by trickeydan** [comment]
> It hasn't, no. But the action is in hand and in progress, so I removed the label. Otherwise the label doesn't really mean anything.

We should probably have a wider discussion about the meanings of these labels. I had interpreted `requires-action` as a kit needing us to do something, rather than being with a team during a cycle

**Comment by RealOrangeOne** [comment]
I will be collecting this kit on Tuesday. Will update inventory and issue once it's in my possession

**Comment by RealOrangeOne** [comment]
JAM's kit is now in my possession. All parts in the inventory are present and correct.

Sadly, quite a few items were missing:

- Battery charger supply
- memory stick
- 3 USB B cables
- 5 micro USB cables
- 10 7.5mm camcons
- 7 5mm camcons

@srobo/kit-committee do we consider this worth continuing to chase?

**Comment by trickeydan** [comment]
> do we consider this worth continuing to chase?

For that list, I would email and ask if they are able to find them. Especially the battery charger PSU as that is an inventoried item.

If they are unable to find the missing parts, let me know and we can decide what to do from there.

**Comment by RealOrangeOne** [comment]
IIRC the charger supply was there, it's just the kettle lead which wasn't. But yes I shall enquire.

**Comment by RealOrangeOne** [comment]
These items are likely lost to time. Closing.
