### ISSUE TITLE
[KLI]: SR2020 LSS

### ISSUE THREAD

**Issue by trickeydan** [srobo/kit-logistics#20]
### Competition Year

SR2020

### Team TLA

LSS

### Asset Code of RUB

1GN24

### How was the kit issued?

In-person (e.g Kickstart)

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by RealOrangeOne** [comment]
The LSS team leader is retiring at Christmas and has been unable to find someone to take over the team. We will need to recover this kit before then, else It'll get much harder.

**Comment by trickeydan** [comment]
I have replied with the UKPostBox address and some packaging instructions.

**Comment by trickeydan** [comment]
The team leader has sent the kit to UKPostBox via tracked and insured post.

**Comment by trickeydan** [comment]
This has been confirmed to be at UK Post box by @Scarzy
