### ISSUE TITLE
[KLI]: SR2022 PSC

### ISSUE THREAD

**Issue by trickeydan** [srobo/kit-logistics#21]
### Competition Year

SR2020

### Team TLA

PSC

### Asset Code of RUB

0UK3G

### How was the kit issued?

In-person (e.g Kickstart)

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by WillB97** [comment]
@trickeydan This team is shown as competing this year (SR2022) and the spreadsheet lists this number as their kit so is this just one that got missed.

**Comment by trickeydan** [comment]
This team has pulled out so the kit needs to be recovered.

**Comment by TomWheal** [comment]
PSC != Winchester College right?

**Comment by trickeydan** [comment]
Returned 0UK3G at competition missing wifi adapter
