### ISSUE TITLE
[KLI]: SR2022 SDC

### ISSUE THREAD

**Issue by trickeydan** [srobo/kit-logistics#24]
### Competition Year

SR2020

### Team TLA

SDC

### Asset Code of RUB

0R6U

### How was the kit issued?

Kit shipped via Courier

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by trickeydan** [comment]
**Transfer to SR2022**

    This team is competing in SR2022 and the kit has been held over.

**Comment by trickeydan** [comment]
Chase email sent after no show.

**Comment by trickeydan** [comment]
Team leader is claiming no knowledge of the kit or SR 😱

**Comment by trickeydan** [comment]
2022 team leader is chasing with the physics department to see if he can find the kit.

**Comment by trickeydan** [comment]
The kit has been found and I have sent instructions to send to UK PostBox.

**Comment by Tyler-Ward** [comment]
This has been processed at the kit sorting day
