### ISSUE TITLE
[KLI]: SR2023 TLC

### ISSUE THREAD

**Issue by trickeydan** [srobo/kit-logistics#30]
### Competition Year

SR2020

### Team TLA

TLC

### Asset Code of RUB

1VM2D

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by trickeydan** [comment]
**Transfer to SR2022**

    This team is competing in SR2022 and the kit has been held over.

**Comment by trickeydan** [comment]
TLC have dropped out.

**Comment by RealOrangeOne** [comment]
Received from team leader:

>  we have 2 SR batteries. I have been through the checklist and everything is there. [..] I might be able to bring the kit (and batteries) over when I next take the ferry to England. Else I guess I shall have to ship the kit and batteries separately.

**Comment by RealOrangeOne** [comment]
I've asked the team supervisor when they'll next be in England RE the above.

**Comment by RealOrangeOne** [comment]
They said June / July, so I've sent the standard shipping instructions, so they'll send the kit to UKPostBox. We'll get the batteries off them later.

**Comment by Tyler-Ward** [comment]
Kit will be reused for SR2023, will ship a new powerboard and brain board to them once required paperwork is complete

**Comment by raccube** [comment]
Handed in at competition.
