### ISSUE TITLE
[KLI]: SR2020 MAI

### ISSUE THREAD

**Issue by trickeydan** [srobo/kit-logistics#31]
### Competition Year

SR2020

### Team TLA

MAI

### Asset Code of RUB

1GL26

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by trickeydan** [comment]
MAI will not be carrying over their kit to SR2022.

This kit will be recovered.

**Comment by raccube** [comment]
MAI's team leader has been contacted.

**Comment by raccube** [comment]
Have not received a response yet.

**Comment by raccube** [comment]
Got a response today, they will be sending out their kit in the next few days.

**Comment by raccube** [comment]
Just sent an email asking for an update.

**Comment by raccube** [comment]
Got a response, they intend on shipping the kit by the end of next week.

**Comment by raccube** [comment]
Update: They are still looking for an appropriate method of shipment

**Comment by raccube** [comment]
Received this kit this morning.
