### ISSUE TITLE
[KLI]: SR2022 HEA

### ISSUE THREAD

**Issue by trickeydan** [srobo/kit-logistics#39]
### Competition Year

SR2022

### Team TLA

HEA

### Asset Code of RUB

1HL24

### How was the kit issued?

Assigned prior to shipping

### Has the inventory been updated?

No

### Has the team signed a kit disclaimer form?

- [X] Yes

### Any other relevant information?

HEA are a new team for SR2022

**Comment by RealOrangeOne** [comment]
HEA damaged their microSD card, and so are being sent a new one.

**Comment by RealOrangeOne** [comment]
HEA may have a damaged ODROID power cable. There may be some damage where the hardened rubber ends on the camcon side. They have checked the camcon is attached correctly.

**Comment by trickeydan** [comment]
Returned 1HL24 at competition
