### ISSUE TITLE
[KLI]: SR2022 BRK

### ISSUE THREAD

**Issue by trickeydan** [srobo/kit-logistics#4]
### Competition Year

SR2020

### Team TLA

BRK

### Asset Code of RUB

1JL22

### How was the kit issued?

In-person (e.g Kickstart)

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by trickeydan** [comment]
**Transfer to SR2022**

    This team is competing in SR2022 and the kit has been held over.

**Comment by trickeydan** [comment]
Partial return at comp

**Comment by trickeydan** [comment]
Kit chase email sent.

**Comment by trickeydan** [comment]
BRK have requested that they return these parts at next kickstart. I have asked for a picture of the parts from the team leader.

**Comment by emersok1** [comment]
I'm led to believe that this is not an issue and team confident of getting kit back?

**Comment by trickeydan** [comment]
> I'm led to believe that this is not an issue and team confident of getting kit back?

Yep. We'll keep the issue open for now so that we don't forget.

**Comment by raccube** [comment]
They handed in. The parts from 2022, they had 3 USB hubs, bought in 2 and will post the 3rd.

**Comment by Tyler-Ward** [comment]
Most of the items marked as in this kit are in my garage or at the competition so this has been processed

I can only see two USB hubs in the kit in 2022 which are both in my garage so I assume the other one has been returned?

@raccube any recollection about this?

**Comment by RealOrangeOne** [comment]
There's nothing marked as with them in the inventory, so we likely got everything back.
