### ISSUE TITLE
[KLI]: SR2022 NMS

### ISSUE THREAD

**Issue by trickeydan** [srobo/kit-logistics#45]
### Competition Year

SR2022

### Team TLA

NMS

### Asset Code of RUB

1NM2R

### How was the kit issued?

Assigned prior to shipping

### Has the inventory been updated?

No

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by trickeydan** [comment]
Chase email sent after no show.

**Comment by trickeydan** [comment]
Confirmation of dispatch received.

**Comment by Tyler-Ward** [comment]
All of the items are in my garage or seen at the competition bar one which is with a 2023 team which hasn't retuned their kit so I think this is done
