### ISSUE TITLE
[KLI]: SR2020 CAT

### ISSUE THREAD

**Issue by trickeydan** [srobo/kit-logistics#5]
### Competition Year

SR2020

### Team TLA

CAT

### Asset Code of RUB

1PN2N

### How was the kit issued?

In-person (e.g Kickstart)

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by emersok1** [comment]
Contacted in by phone & Email June. JdeB still primary contact.  Chased via college phone on 24/06

**Comment by emersok1** [comment]
I picked the kit up on Saturday 25 June. All parts checked against the appropriate kit list (Apart from a screwdriver, which I wasn't going to quibble about!) Kit looks to be in good condition (probably unused), although I haven't tried any of it. I'll do this if I get a chance. Not sure what to do about the status "lozenges" e.g. requires-action etc

**Comment by RealOrangeOne** [comment]
Given we have the kit in our possession now, we can close the issue. Great work!

**Comment by emersok1** [comment]
Basic test of hardware completed: Latest firmware runs on Odroid. All modules detected with correct designations. Hubs OK (not all ports checked), Power board appears OK, Motor boards run motors (both directions), Servo board runs  a servo, Ruggeduino operates an LED (one output only checked). Most USB cables(those used to connect to the HUB, Odroid  etc above) OK
