### ISSUE TITLE
[KLI]: SR2022 PHC

### ISSUE THREAD

**Issue by raccube** [srobo/kit-logistics#53]
### Competition Year

SR2022

### Team TLA

PHC

### Asset Code of RUB

sr1JM21

### How was the kit issued?

Assigned prior to shipping

### Has the inventory been updated?

No

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by trickeydan** [comment]
Chase email sent after no show.

**Comment by trickeydan** [comment]
Another chase sent.

**Comment by emersok1** [comment]
School contacted by phone 20 June 2022. KE provided home phone number and asked for nominated contact at school to contact

**Comment by emersok1** [comment]
Provided with KE google mail and asked to contact KE

**Comment by emersok1** [comment]
Sent return info (return address) by Email on 24/06. They replied that is in their dispatch office and will be ready to ship on Monday 27/06. Dan asked Scarzy if UKPOSTBOX confirm receipt

**Comment by emersok1** [comment]
Shipped from PHC (to Poole address) on 5th July
[parcel proof (1).pdf](https://github.com/srobo/kit-logistics/files/9065413/parcel.proof.1.pdf)

**Comment by trickeydan** [comment]
This has been delivered according to ParcelForce tracking.
