### ISSUE TITLE
[Shipping]: SR2022 PHC

### ISSUE THREAD

**Issue by raccube** [srobo/kit-logistics#54]
### Kit Logistics Issue

#53

### Team TLA

PHC

### What country is the team located in?

GB

### Where can the address be located?

SR2022 Teams Organisation Sheet

**Comment by RealOrangeOne** [comment]
@raccube has this kit been dispatched?

**Comment by raccube** [comment]
> @raccube has this kit been dispatched?

Not yet. Will update once it has.

**Comment by antoinepetty** [comment]
Waiting on the courier to dispatch (https://studentrobotics.slack.com/archives/CD6C80TRD/p1642628508014500?thread_ts=1642628092.013900&cid=CD6C80TRD)

**Comment by trickeydan** [comment]
I have sent an email to the courier to find out the status.

**Comment by trickeydan** [comment]
The courier has confirmed that this kit was sent and received.
