### ISSUE TITLE
[KLI]: SR2023 ABS

### ISSUE THREAD

**Issue by trickeydan** [srobo/kit-logistics#55]
### Competition Year

SR2023

### Team TLA

ABS

### Asset Code of RUB

sr0Y5P

### How was the kit issued?

In-person (e.g Kickstart)

### Has the inventory been updated?

No

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by trickeydan** [comment]
Kit issued to teacher in person at Kickstart.

**Comment by raccube** [comment]
Handed in at competition, missing CamCons.
