### ISSUE TITLE
[KLI]: SR2023 CCR

### ISSUE THREAD

**Issue by trickeydan** [srobo/kit-logistics#56]
### Competition Year

SR2023

### Team TLA

CCR

### Asset Code of RUB

FQ34

### How was the kit issued?

In-person (e.g Kickstart)

### Has the inventory been updated?

No

### Has the team signed a kit disclaimer form?

- [X] Yes

### Any other relevant information?

Handed to Keith E at Kickstart

**Comment by raccube** [comment]
This was handed in by @emersok1
