### ISSUE TITLE
[KLI]: SR2023 HZW

### ISSUE THREAD

**Issue by raccube** [srobo/kit-logistics#59]
### Competition Year

SR2023

### Team TLA

HZW

### Asset Code of RUB

sr1GN24

### How was the kit issued?

In-person (e.g Kickstart)

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by trickeydan** [comment]
Dropped out, kit returned to @sedders123
