### ISSUE TITLE
[KLI]: SR2023 CLY

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/kit-logistics#68]
### Competition Year

SR2023

### Team TLA

CLY

### Asset Code of RUB

0H63

### How was the kit issued?

Other (please add info below)

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

### Any other relevant information?

Kit sent via Trustee

**Comment by raccube** [comment]
Handed in at competition.
