### ISSUE TITLE
[KLI]: SR2023 CNN

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/kit-logistics#71]
### Competition Year

SR2023

### Team TLA

CNN

### Asset Code of RUB

sr0T5V

### How was the kit issued?

Assigned prior to shipping

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by raccube** [comment]
Team was a no-show but someone stopped by to hand in the kit
