### ISSUE TITLE
[KLI]: SR2023 ELC

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/kit-logistics#72]
### Competition Year

SR2023

### Team TLA

ELC

### Asset Code of RUB

sr0T6T

### How was the kit issued?

Assigned prior to shipping

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by raccube** [comment]
Handed in at competition, except screwdriver.
