### ISSUE TITLE
[KLI]: SR2023 HAM

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/kit-logistics#75]
### Competition Year

SR2023

### Team TLA

HAM

### Asset Code of RUB

sr1MM2U

### How was the kit issued?

Assigned prior to shipping

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by raccube** [comment]
Handed in at comp. Was missing a MicroCamCon.
