### ISSUE TITLE
[KLI]: SR2023 HWM

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/kit-logistics#77]
### Competition Year

SR2023

### Team TLA

HWM

### Asset Code of RUB

sr1PN2N

### How was the kit issued?

Assigned prior to shipping

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by raccube** [comment]
Handed in at competition, missing screwdriver and 2 micro USB cables.
