### ISSUE TITLE
[KLI]: SR2024 ABS

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/kit-logistics#88]
### Competition Year

SR2024

### Team TLA

ABS

### Asset Code of RUB

sr0H63

### How was the kit issued?

Kit shipped via Courier

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by mgrove36** [comment]
USB stick missing

**Comment by RealOrangeOne** [comment]
Re-opening so we (I) remember to send them a softer email about looking for the USB

**Comment by RealOrangeOne** [comment]
Initial kit return email sent.

**Comment by RealOrangeOne** [comment]
We've not heard anything from them. If it turns up, great. Otherwise we'll consider it a consumable part and purchase more when we need it.
