### ISSUE TITLE
[KLI]: SR2020 CUS

### ISSUE THREAD

**Issue by trickeydan** [srobo/kit-logistics#9]
### Competition Year

SR2020

### Team TLA

CUS

### Asset Code of RUB

OX5Q

### How was the kit issued?

Kit shipped via Courier

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by trickeydan** [comment]
This team appears to have requested a return, and was marked as resolved in the spreadsheet. However, we have no record in the inventory of it having been returned.

@tomwheal Do you know what happened here?

**Comment by TomWheal** [comment]
Rob is the person to ask here, I can't take @ him but I'll send him this issue

**Comment by rgilton** [comment]
Either it was in the batch of kits that got returned, or it was not received from the team.  The team responded to the email I sent them asking if they want to compete in SR2022 or return the kit.  They opted to return the kit.  I sent return details, then didn't hear from them again.

**Comment by emersok1** [comment]
Contacted June. JC contact still there. Sent Email giving return info

**Comment by emersok1** [comment]
Received this today 07/07
The label shown in the previous image was the address provided for return last year before the parcel fell into a void. (Venture House Letchworth)
Having found it there has been a bit of a struggle with our new finance system to sort shipping which means it has not yet been collected (collection due today)
As such I will endeavour to get the address changed to the new one you have provided and your number as the contact.
I will update you when the parcel has shipped.

**Comment by RealOrangeOne** [comment]
This kit was present at a kit packing event in 2023, so assumed to have been returned.
