### ISSUE TITLE
[KLI]: SR2024 CLY

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/kit-logistics#91]
### Competition Year

SR2024

### Team TLA

CLY

### Asset Code of RUB

srFT32

### How was the kit issued?

Kit shipped via Courier

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by raccube** [comment]
Kit completely handed back but camera and motor board are defective.
