### ISSUE TITLE
[KLI]: SR2024 ELC

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/kit-logistics#92]
### Competition Year

SR2024

### Team TLA

ELC

### Asset Code of RUB

0R6U

### How was the kit issued?

Kit shipped via Courier

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by mgrove36** [comment]
RUB lid missing

**Comment by RealOrangeOne** [comment]
Initial kit return email sent.

**Comment by RealOrangeOne** [comment]
>  We have checked here and can't find. It definitely made it to Southampton, and never back with us. Really sorry, but we're going to have to declare it lost.

**Comment by RealOrangeOne** [comment]
We're unlikely to get this back, if it's even still lost. Closing.
