### ISSUE TITLE
[KLI]: SR2024 HBS

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/kit-logistics#98]
### Competition Year

SR2024

### Team TLA

HBS

### Asset Code of RUB

0WK3C

### How was the kit issued?

Kit shipped via Courier

### Has the inventory been updated?

Yes

### Has the team signed a kit disclaimer form?

- [X] Yes

**Comment by mgrove36** [comment]
Kit handed in on Saturday

**Comment by mgrove36** [comment]
Checked kit. It is now with the other RUBs.
1x micro USB cable missing
